/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOnboardSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-onboard',
    description: 'Guided onboarding for OpenSpec - walk through a complete workflow cycle with narration and real codebase work.',
    instructions: getOnboardInstructions(),
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

function getOnboardInstructions(): string {
  return `Guide the user through their first complete OpenSpec workflow cycle. This is a teaching experience—you'll do real work in their codebase while explaining each step.

---

## Preflight

Before starting, check if the OpenSpec CLI is installed:

\`\`\`bash
# Unix/macOS
openspec --version 2>&1 || echo "CLI_NOT_INSTALLED"
# Windows (PowerShell)
# if (Get-Command openspec -ErrorAction SilentlyContinue) { openspec --version } else { echo "CLI_NOT_INSTALLED" }
\`\`\`

**If CLI not installed:**
> OpenSpec CLI is not installed. Install it first, then come back to \`/opsx:onboard\`.

Stop here if not installed.

---

## Phase 1: Welcome

Display:

\`\`\`
## Welcome to OpenSpec!

I'll walk you through a complete change cycle—from idea to implementation—using a real task in your codebase. Along the way, you'll learn the workflow by doing it.

**What we'll do:**
1. Pick a small, real task in your codebase
2. Create a change (the container for our work)
3. Explore the problem (mandatory before proposal)
4. Build the artifacts: proposal → specs → design → tasks (6-step TDD embedded)
5. Implement the tasks (TDD enforced per task)
6. Archive the completed change

**Time:** ~15-20 minutes

Let's start by finding something to work on.
\`\`\`

---

## Phase 2: Task Selection

### Codebase Analysis

Scan the codebase for small improvement opportunities. Look for:

1. **TODO/FIXME comments** - Search for \`TODO\`, \`FIXME\`, \`HACK\`, \`XXX\` in code files
2. **Missing error handling** - \`catch\` blocks that swallow errors, risky operations without try-catch
3. **Functions without tests** - Cross-reference \`src/\` with test directories
4. **Type issues** - \`any\` types in TypeScript files (\`: any\`, \`as any\`)
5. **Debug artifacts** - \`console.log\`, \`console.debug\`, \`debugger\` statements in non-debug code
6. **Missing validation** - User input handlers without validation

Also check recent git activity:
\`\`\`bash
# Unix/macOS
git log --oneline -10 2>/dev/null || echo "No git history"
# Windows (PowerShell)
# git log --oneline -10 2>$null; if ($LASTEXITCODE -ne 0) { echo "No git history" }
\`\`\`

### Present Suggestions

From your analysis, present 3-4 specific suggestions:

\`\`\`
## Task Suggestions

Based on scanning your codebase, here are some good starter tasks:

**1. [Most promising task]**
   Location: \`src/path/to/file.ts:42\`
   Scope: ~1-2 files, ~20-30 lines
   Why it's good: [brief reason]

**2. [Second task]**
   Location: \`src/another/file.ts\`
   Scope: ~1 file, ~15 lines
   Why it's good: [brief reason]

**3. [Third task]**
   Location: [location]
   Scope: [estimate]
   Why it's good: [brief reason]

**4. Something else?**
   Tell me what you'd like to work on.

Which task interests you? (Pick a number or describe your own)
\`\`\`

**If nothing found:** Fall back to asking what the user wants to build:
> I didn't find obvious quick wins in your codebase. What's something small you've been meaning to add or fix?

### Scope Guardrail

If the user picks or describes something too large (major feature, multi-day work):

\`\`\`
That's a valuable task, but it's probably larger than ideal for your first OpenSpec run-through.

For learning the workflow, smaller is better—it lets you see the full cycle without getting stuck in implementation details.

**Options:**
1. **Slice it smaller** - What's the smallest useful piece of [their task]? Maybe just [specific slice]?
2. **Pick something else** - One of the other suggestions, or a different small task?
3. **Do it anyway** - If you really want to tackle this, we can. Just know it'll take longer.

What would you prefer?
\`\`\`

Let the user override if they insist—this is a soft guardrail.

---

## Phase 3: Create the Change

**EXPLAIN:**
\`\`\`
## Creating a Change

A "change" in OpenSpec is a container for all the thinking and planning around a piece of work. It lives in \`openspec/changes/<name>/\` and holds your artifacts—explore.md, proposal, specs, design, tasks.

Let me create one for our task.
\`\`\`

**DO:** Create the change with a derived kebab-case name:
\`\`\`bash
openspec new change "<derived-name>"
\`\`\`

**SHOW:**
\`\`\`
Created: \`openspec/changes/<name>/\`

The folder starts with just a \`.openspec.yaml\` metadata file. We'll add artifacts next — first explore, then proposal, specs, design, and tasks.
\`\`\`

---

## Phase 4: Explore Demo

Once the change exists, demonstrate explore mode — the mandatory first step before creating any proposal:

\`\`\`
Now let me show you **explore mode** — it's the mandatory first step before we can create a proposal. It's how you investigate the problem, compare options, and document your thinking.
\`\`\`

Spend 1-2 minutes investigating the relevant code:
- Read the file(s) involved
- Note key insights and options
- Draw a quick ASCII diagram if it helps

\`\`\`
## Quick Exploration

[Your brief analysis—what you found, any considerations]

┌─────────────────────────────────────────┐
│   [Optional: ASCII diagram if helpful]  │
└─────────────────────────────────────────┘

Explore mode (\`/opsx:explore\`) creates \`explore.md\` in the change — this is the required prerequisite for proposal. The proposal will reference these findings when making decisions.

Now let's create the proposal.
\`\`\`

**PAUSE** - Wait for user acknowledgment before proceeding.

---

## Phase 5: Proposal

**EXPLAIN:**
\`\`\`
## The Proposal

The proposal captures **why** we're making this change, **what** approach we chose, and **what** it involves at a high level. It builds on the explore findings to make a concrete decision.

I'll draft one based on our task.
\`\`\`

**DO:** Draft the proposal content (don't save yet):

\`\`\`
Here's a draft proposal:

---

## Why

[1-2 sentences explaining the problem/opportunity]

## What Changes

[Bullet points of what will be different]

## Non-Goals

[What's explicitly OUT of scope — prevents scope creep]

## Decision

[Why this approach? Summary of the key trade-off from explore.
 Reference alternatives considered and why they were rejected.]

## Capabilities

### New Capabilities
- \`<capability-name>\`: [what this covers — behavior, scope, key scenarios]

### Modified Capabilities
<!-- Only if spec-level requirements change -->

## Impact

- \`src/path/to/file.ts\`: [what changes]
- [other files if applicable]

---

Does this capture the intent? I can adjust before we save it.
\`\`\`

**PAUSE** - Wait for user approval/feedback.

After approval, save the proposal:
\`\`\`bash
openspec instructions proposal --change "<name>" --json
\`\`\`
Then write the content to \`openspec/changes/<name>/proposal.md\`.

\`\`\`
Proposal saved. This is your "why" document—you can always come back and refine it as understanding evolves.

Next up: specs.
\`\`\`

---

## Phase 6: Specs

**EXPLAIN:**
\`\`\`
## Specs

Specs define **what** we're building in precise, testable terms. They use a requirement/scenario format that makes expected behavior crystal clear.

For a small task like this, we might only need one spec file.
\`\`\`

**DO:** Create the spec file:
\`\`\`bash
# Unix/macOS
mkdir -p openspec/changes/<name>/specs/<capability-name>
# Windows (PowerShell)
# New-Item -ItemType Directory -Force -Path "openspec/changes/<name>/specs/<capability-name>"
\`\`\`

Draft the spec content:

\`\`\`
Here's the spec:

---

## ADDED Requirements

### Requirement: <Name>

<Description of what the system should do>

#### Scenario: <Scenario name>

- **WHEN** <trigger condition>
- **THEN** <expected outcome>
- **AND** <additional outcome if needed>

---

This format—WHEN/THEN/AND—makes requirements testable. You can literally read them as test cases.
\`\`\`

Save to \`openspec/changes/<name>/specs/<capability>/spec.md\`.

---

## Phase 7: Design

**EXPLAIN:**
\`\`\`
## Design

The design captures **how** we'll build it—technical decisions, tradeoffs, approach.

For small changes, this might be brief. That's fine—not every change needs deep design discussion.
\`\`\`

**DO:** Draft design.md:

\`\`\`
Here's the design:

---

## Context

[Brief context about the current state]

## Goals / Non-Goals

**Goals:**
- [What we're trying to achieve]

**Non-Goals:**
- [What's explicitly out of scope]

## Decisions

### Decision 1: [Key decision]

[Explanation of approach and rationale]

---

For a small task, this captures the key decisions without over-engineering.
\`\`\`

Save to \`openspec/changes/<name>/design.md\`.

---

## Phase 8: Tasks

**EXPLAIN:**
\`\`\`
## Tasks

Now we break the work into implementation tasks. Each task embeds the full TDD cycle as sub-steps — this is mandatory and enforced by the apply workflow.
\`\`\`

**DO:** Generate tasks based on specs and design:

\`\`\`
Here are the implementation tasks (each with embedded TDD sub-steps):

---

## 1. [Category or file]

- [ ] 1.1 [Specific task]
  - [ ] RED: Write one failing test for <behavior>
  - [ ] Verify RED: Run test, confirm it fails correctly
  - [ ] GREEN: Write minimum code to pass
  - [ ] Verify GREEN: Run test, confirm pass + no regressions
  - [ ] REFACTOR: Clean up, keep tests green
  - [ ] SIMPLIFY: Review changed files for clarity

- [ ] 1.2 [Another task]
  - [ ] RED: Write one failing test for <behavior>
  - [ ] Verify RED: Run test, confirm it fails correctly
  - [ ] GREEN: Write minimum code to pass
  - [ ] Verify GREEN: Run test, confirm pass + no regressions
  - [ ] REFACTOR: Clean up, keep tests green
  - [ ] SIMPLIFY: Review changed files for clarity

---

**The Iron Law**: NO PRODUCTION CODE WITHOUT A FAILING TEST FIRST. TDD is enforced — the 6 sub-steps cannot be skipped. Each step has a checkbox that gets checked off during apply.

Ready to implement?
\`\`\`

**PAUSE** - Wait for user to confirm they're ready to implement.

Save to \`openspec/changes/<name>/tasks.md\`.

---

## Phase 9: Apply (Implementation)

**EXPLAIN:**
\`\`\`
## Implementation

Now we implement each task following the embedded TDD cycle. The apply workflow acts as an outer-loop controller — process one task at a time through RED → Verify RED → GREEN → Verify GREEN → REFACTOR → SIMPLIFY.
\`\`\`

**DO:** For each task:

1. Announce: "Working on task N: [description]"
2. Follow the 6 TDD sub-steps in order (RED → Verify RED → GREEN → Verify GREEN → REFACTOR → SIMPLIFY)
3. Reference specs/design naturally: "The spec says X, so I'm doing Y"
4. Mark each sub-step checkbox \`- [x]\` as you complete it
5. After all 6 sub-steps done: C0 check → mark task complete → commit → next task
6. Brief status: "✓ Task N complete"

Keep narration light—don't over-explain every line of code. But do mention the key TDD checkpoints.

After all tasks:

\`\`\`
## Implementation Complete

All tasks done:
- [x] Task 1 (6/6 TDD sub-steps ✓)
- [x] Task 2 (6/6 TDD sub-steps ✓)
- [x] ...

The change is implemented! One more step—let's archive it.
\`\`\`

---

## Phase 10: Archive

**EXPLAIN:**
\`\`\`
## Archiving

When a change is complete, we archive it. This moves it from \`openspec/changes/\` to \`openspec/changes/archive/YYYY-MM-DD-<name>/\`.

Archived changes become your project's decision history—you can always find them later to understand why something was built a certain way.
\`\`\`

**DO:**
\`\`\`bash
openspec archive "<name>"
\`\`\`

**SHOW:**
\`\`\`
Archived to: \`openspec/changes/archive/YYYY-MM-DD-<name>/\`

The change is now part of your project's history. The code is in your codebase, the decision record is preserved.
\`\`\`

---

## Phase 11: Recap & Next Steps

\`\`\`
## Congratulations!

You just completed a full OpenSpec cycle:

1. **New** - Created a change container
2. **Explore** - Investigated the problem (mandatory before proposal)
3. **Proposal** - Captured WHY + decision
4. **Specs** - Defined WHAT in detail
5. **Design** - Decided HOW + file structure
6. **Tasks** - Broke into 6-step TDD checklist
7. **Apply** - Implemented with TDD enforced per task
8. **Archive** - Preserved the record

This same rhythm works for any size change—a small fix or a major feature.

---

## Command Reference

**Core workflow:**

 | Command           | What it does                                    |
 |-------------------|-------------------------------------------------|
 | \`/opsx:explore\` | Investigate problems (mandatory before propose) |
 | \`/opsx:propose\` | Create a change and generate all artifacts      |
 | \`/opsx:apply\`   | Implement tasks with TDD enforced               |
 | \`/opsx:verify\`  | Verify implementation matches artifacts         |
 | \`/opsx:archive\` | Archive a completed change                      |

**Additional commands:**

 | Command            | What it does                                             |
 |--------------------|----------------------------------------------------------|
 | \`/opsx:new\`      | Start a new change, step through artifacts one at a time |
 | \`/opsx:continue\` | Continue working on an existing change                   |
 | \`/opsx:ff\`       | Fast-forward: create all artifacts at once               |
 | \`/opsx:review\`   | Code review with complexity-adaptive depth               |
 | \`/opsx:sync\`     | Sync delta specs to main specs                           |

---

## What's Next?

Try \`/opsx:propose\` on something you actually want to build. You've got the rhythm now!
\`\`\`

---

## Graceful Exit Handling

### User wants to stop mid-way

If the user says they need to stop, want to pause, or seem disengaged:

\`\`\`
No problem! Your change is saved at \`openspec/changes/<name>/\`.

To pick up where we left off later:
- \`/opsx:continue <name>\` - Resume artifact creation
- \`/opsx:apply <name>\` - Jump to implementation (if tasks exist)

The work won't be lost. Come back whenever you're ready.
\`\`\`

Exit gracefully without pressure.

### User just wants command reference

If the user says they just want to see the commands or skip the tutorial:

\`\`\`
## OpenSpec Quick Reference

**Core workflow:**

 | Command                  | What it does                                    |
 |--------------------------|-------------------------------------------------|
 | \`/opsx:explore\`        | Investigate problems (mandatory before propose) |
 | \`/opsx:propose <name>\` | Create a change and generate all artifacts      |
 | \`/opsx:apply <name>\`   | Implement tasks with TDD enforced               |
 | \`/opsx:verify <name>\`  | Verify implementation                           |
 | \`/opsx:archive <name>\` | Archive when done                               |

**Additional commands:**

 | Command                   | What it does                        |
 |---------------------------|-------------------------------------|
 | \`/opsx:new <name>\`      | Start a new change, step by step    |
 | \`/opsx:continue <name>\` | Continue an existing change         |
 | \`/opsx:ff <name>\`       | Fast-forward: all artifacts at once |
 | \`/opsx:review <name>\`   | Code review                         |
 | \`/opsx:sync <name>\`     | Sync specs to main                  |

Try \`/opsx:explore\` to start, then \`/opsx:propose\` to create your first change.
\`\`\`

Exit gracefully.

---

## Guardrails

- **Follow the EXPLAIN → DO → SHOW → PAUSE pattern** at key transitions (after explore, after proposal draft, after tasks, after archive)
- **Keep narration light** during implementation—teach without lecturing
- **Don't skip phases** even if the change is small—the goal is teaching the workflow
- **Pause for acknowledgment** at marked points, but don't over-pause
- **Handle exits gracefully**—never pressure the user to continue
- **Use real codebase tasks**—don't simulate or use fake examples
- **Adjust scope gently**—guide toward smaller tasks but respect user choice`;
}

export function getOpsxOnboardCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Onboard',
    description: 'Guided onboarding - walk through a complete OpenSpec workflow cycle with narration',
    category: 'Workflow',
    tags: ['workflow', 'onboarding', 'tutorial', 'learning'],
    content: getOnboardInstructions(),
  };
}
